on:
  push:
    tags:
      - "v*"

name: Release
jobs:
  release:
    name: Release GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm i -g jdoc
      - run: npm run docs
      - uses: technote-space/release-github-actions@v6
