on:
# Check every time a pull request is made in every branch
  pull_request:
    branches:
      - '*'

name: Test Unit
jobs:
  docs:
    name: Generate documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install JSDoc
        run: npm i jsdoc -g
      - name: Generate documentation
        run: npm run docs-gh

  release:
    name: Test Unit
    needs: docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci & npm i jest -g
      - name: Run tests
        run: npm run test